sudo: required
services:
  - docker

before_install
  - docker build -t gauravanand/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gauravanand/react-test npm test -- --coverage

after_success:
  - docker build -t gauravanand/multi-client ./client
  - docker build -t gauravanand/multi-nginx ./nginx
  - docker build -t gauravanand/multi-server ./server
  - docker build -t gauravanand/multi-worker ./worker
  #Login into docker CLI
  - echo  "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gauravanand/multi-client 
  - docker push gauravanand/multi-nginx
  - docker push gauravanand/multi-server
  - docker push gauravanand/multi-worker